"""Type stubs for the PyO3-backed `daisy._daisy` extension module.

Hand-written; keep in sync with `daisy-py/src/*.rs`. The `_daisy`
extension is built by maturin; static type checkers (ty, mypy,
pyright) read this `.pyi` instead of trying to introspect the
compiled `.so`.
"""

from collections.abc import Iterable, Iterator
from pathlib import Path
from typing import Any, Callable, Self

# -- Geometry primitives ------------------------------------------------

class Coordinate:
    def __init__(self, values: Iterable[int]) -> None: ...
    @property
    def dims(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[int]: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: Coordinate) -> Coordinate: ...
    def __sub__(self, other: Coordinate) -> Coordinate: ...
    def __neg__(self) -> Coordinate: ...
    def to_list(self) -> list[int]: ...

class Roi:
    def __init__(self, offset: Iterable[int], shape: Iterable[int]) -> None: ...
    @property
    def offset(self) -> Coordinate: ...
    @property
    def shape(self) -> Coordinate: ...
    @property
    def begin(self) -> Coordinate: ...
    @property
    def end(self) -> Coordinate: ...
    @property
    def dims(self) -> int: ...
    def contains(self, other: Roi | Coordinate) -> bool: ...
    def intersects(self, other: Roi) -> bool: ...
    def intersect(self, other: Roi) -> Roi: ...
    def grow(
        self,
        amount_neg: Coordinate | Iterable[int],
        amount_pos: Coordinate | Iterable[int],
    ) -> Roi: ...
    def translate(self, by: Coordinate | Iterable[int]) -> Roi: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

# -- Blocks -------------------------------------------------------------

class BlockStatus:
    CREATED: BlockStatus
    PROCESSING: BlockStatus
    SUCCESS: BlockStatus
    FAILED: BlockStatus
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class BlockStats:
    """What one block cost. `gpu_*` are reserved and read NaN / 0."""

    @property
    def wall_seconds(self) -> float: ...
    @property
    def cpu_seconds(self) -> float: ...
    @property
    def peak_rss_bytes(self) -> int: ...
    @property
    def io_read_bytes(self) -> int: ...
    @property
    def io_write_bytes(self) -> int: ...
    @property
    def gpu_util_pct(self) -> float: ...
    @property
    def gpu_mem_bytes(self) -> int: ...

class BlockProfile:
    def __enter__(self) -> BlockProfile: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: object | None = ...,
    ) -> bool: ...

def profile_block(block: Block) -> BlockProfile: ...
def measure_block_stats(block: Block, f: Callable[[Block], Any]) -> Any: ...
def _measure_now() -> BlockStats: ...

class Block:
    # PyO3 wires the constructor as __new__; declare it (not just
    # __init__) so subclasses' super().__new__(cls, ...) type-checks.
    def __new__(
        cls,
        total_roi: Roi,
        read_roi: Roi,
        write_roi: Roi,
        task_id: str | None = ...,
        block_id: int | None = ...,
    ) -> Self: ...
    @property
    def total_roi(self) -> Roi: ...
    @property
    def read_roi(self) -> Roi: ...
    @property
    def write_roi(self) -> Roi: ...
    @property
    def block_id(self) -> tuple[str, int]: ...
    @property
    def task_id(self) -> str: ...
    status: BlockStatus
    # Measured by whoever ran the block; rides home on the release message.
    stats: BlockStats | None
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# -- Task state ---------------------------------------------------------

DEFAULT_BLOCK_TIMEOUT_SECS: float

class TaskState:
    @property
    def started(self) -> bool: ...
    @property
    def total_block_count(self) -> int: ...
    @property
    def ready_count(self) -> int: ...
    @property
    def processing_count(self) -> int: ...
    @property
    def completed_count(self) -> int: ...
    @property
    def skipped_count(self) -> int: ...
    @property
    def failed_count(self) -> int: ...
    @property
    def orphaned_count(self) -> int: ...
    @property
    def pending_count(self) -> int: ...
    @property
    def worker_failure_count(self) -> int: ...
    @property
    def worker_restart_count(self) -> int: ...
    @property
    def abandoned(self) -> bool: ...
    @property
    def abandon_reason(self) -> str | None: ...
    @property
    def last_worker_error(self) -> str | None: ...
    @property
    def first_worker_error(self) -> str | None: ...
    def worker_start_count(self) -> int: ...
    @property
    def timeout_reclaim_count(self) -> int: ...
    @property
    def timeout_secs(self) -> float | None: ...
    def is_done(self) -> bool: ...

# -- Task ---------------------------------------------------------------

class Task:
    # `__new__` is what PyO3 wires up for `#[new]`; declare it (not
    # `__init__`) so that v1_compat's `super().__new__(cls, *args,
    # **kwargs)` resolves to a signature the type checker recognises.
    def __new__(
        cls,
        task_id: str,
        total_roi: Roi,
        read_roi: Roi,
        write_roi: Roi,
        process_function: Callable[..., Any] | None = ...,
        check_function: Callable[..., Any] | None = ...,
        read_write_conflict: bool = ...,
        fit: str = ...,
        max_workers: int = ...,
        max_retries: int = ...,
        timeout: float | int | object | None = ...,
        done_marker_path: str | bool | None = ...,
        resource_tracking: bool = ...,
        requires: dict[str, int] | None = ...,
        max_worker_restarts: int = ...,
    ) -> Self: ...

    # Read-only views of the constructor args.
    @property
    def task_id(self) -> str: ...
    @property
    def total_roi(self) -> Roi: ...
    @property
    def read_roi(self) -> Roi: ...
    @property
    def write_roi(self) -> Roi: ...
    @property
    def fit(self) -> str: ...
    @property
    def read_write_conflict(self) -> bool: ...
    @property
    def max_workers(self) -> int: ...
    @property
    def max_retries(self) -> int: ...
    @property
    def max_worker_restarts(self) -> int: ...
    @property
    def timeout_secs(self) -> float | None: ...
    @property
    def requires(self) -> dict[str, int]: ...
    @property
    def done_marker_path(self) -> str | bool | None: ...
    @property
    def resource_tracking(self) -> bool: ...

    # Settable so `_wrap_for_worker_logging` can replace the callable
    # on a clone produced by `copy.copy(task)`.
    process_function: Callable[..., Any] | None
    check_function: Callable[..., Any] | None

    def reset(self) -> str | None: ...
    def __copy__(self) -> Task: ...
    def __deepcopy__(self, memo: Any) -> Task: ...

    # Pipeline composition.
    def __add__(self, other: Task | Pipeline) -> Pipeline: ...
    def __or__(self, other: Task | Pipeline) -> Pipeline: ...

# -- Pipeline -----------------------------------------------------------

class Pipeline:
    def __init__(
        self,
        tasks: list[Task] | None = ...,
        edges: list[tuple[Task, Task]] | None = ...,
    ) -> None: ...
    @staticmethod
    def from_task(task: Task) -> Pipeline: ...
    @property
    def tasks(self) -> list[Task]: ...
    @property
    def sources(self) -> list[Task]: ...
    @property
    def outputs(self) -> list[Task]: ...
    @property
    def edges(self) -> list[tuple[Task, Task]]: ...
    def reset(self) -> None: ...
    def run_blockwise(
        self,
        *,
        multiprocessing: bool = ...,
        resources: dict[str, int] | None = ...,
        progress: bool | object | None = ...,
        block_tracking: bool = ...,
    ) -> bool: ...
    def __add__(self, other: Task | Pipeline) -> Pipeline: ...
    def __or__(self, other: Task | Pipeline) -> Pipeline: ...
    def __radd__(self, other: Task | Pipeline) -> Pipeline: ...
    def __ror__(self, other: Task | Pipeline) -> Pipeline: ...
    def __repr__(self) -> str: ...

# -- Dependency graph ---------------------------------------------------

class BlockwiseDependencyGraph:
    def __init__(
        self,
        task_id: str,
        block_read_roi: Roi,
        block_write_roi: Roi,
        read_write_conflict: bool,
        fit: str,
        total_read_roi: Roi | None = ...,
        total_write_roi: Roi | None = ...,
    ) -> None: ...
    @property
    def num_blocks(self) -> int: ...
    @property
    def num_levels(self) -> int: ...
    @property
    def num_roots(self) -> int: ...
    def root_gen(self) -> Iterator[Block]: ...
    def upstream(self, block: Block) -> list[Block]: ...
    def downstream(self, block: Block) -> list[Block]: ...
    def get_subgraph_blocks(self, sub_roi: Roi) -> list[Block]: ...
    def enumerate_all_dependencies(self) -> Iterator[Block]: ...

class DependencyGraph:
    def upstream(self, block: Block) -> list[Block]: ...
    def downstream(self, block: Block) -> list[Block]: ...

# -- Scheduler ----------------------------------------------------------

class Scheduler:
    def __init__(self, input: Pipeline | Task) -> None: ...
    def acquire_block(self, task_id: str) -> Block | None: ...
    def release_block(self, block: Block) -> None: ...
    @property
    def task_states(self) -> dict[str, TaskState]: ...
    @property
    def dependency_graph(self) -> DependencyGraph: ...

# -- Client / Context (worker-side) -------------------------------------

class Context:
    ENV_VARIABLE: str
    def __init__(self, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __contains__(self, key: object) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def copy(self) -> Context: ...
    def to_env(self) -> str: ...
    @staticmethod
    def from_env() -> Context: ...
    def __repr__(self) -> str: ...

class SyncClient:
    def __init__(self, host: str, port: int, task_id: str) -> None: ...
    def acquire_block(self) -> Block | None: ...
    def release_block(self, block: Block) -> None: ...
    def report_failure(self, block: Block, error: str) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

# -- Module-level functions --------------------------------------------

def set_done_marker_basedir(path: str | None) -> None: ...
def get_done_marker_basedir() -> Path | None: ...
def _run_serial(
    input: Pipeline | Task,
    block_tracking: bool = ...,
) -> dict[str, TaskState]: ...
def _run_distributed_server(
    input: Pipeline | Task,
    resources: dict[str, int] | None = ...,
    progress_observer: object | None = ...,
    host: str = ...,
    block_tracking: bool = ...,
) -> tuple[dict[str, TaskState], dict[str, Any]]: ...
def _run_blockwise_orchestrator(
    input: Pipeline | Task,
    multiprocessing: bool = ...,
    resources: dict[str, int] | None = ...,
    progress: bool | object | None = ...,
    block_tracking: bool = ...,
) -> dict[str, TaskState]: ...
def _topo_order(input: Pipeline | Task) -> list[str]: ...
