name: Python Black

on: [push, pull_request]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Setup checkout
        uses: actions/checkout@master
      - name: Lint with Black
        run: |
          pip install black
          black funlib/persistence tests --diff --check
