name: Generate Pages

on:
  push:
    branches:
      - update-docs

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Turn script into notebook
      run: |
        uv run --extra docs python -m ipykernel install --name daisy_env --user
        uv run --extra docs jupytext --to notebook --execute ./docs/source/notebooks/tutorial.py --output ./docs/source/notebooks/tutorial.ipynb
    - name: Build
      run: uv run --extra docs sphinx-build docs/source/ docs/build/html -b html
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifact_name: html-docs
