name: Generate Pages

on:
  push:
    # tags: ["*"]
    branches:
      - update-docs

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc
    - name: Turn script into notebook
      run: |
        uv run --extra docs python -m ipykernel install --name daisy_env --user
        uv run --extra docs jupytext --to notebook ./examples/tutorial.py
        mv ./examples/tutorial.ipynb ./docs/source/tutorial.ipynb
    - name: Build
      run: uv run --extra docs sphinx-build docs/source/ docs/build/html -b html
    - name: Set permissions
      run: chmod -R a+rX ./docs/build/html
    - name: Update gh branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html