name: Python mypy

on: [push, pull_request]

jobs:
  static-analysis:
    name: Python mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: mypy
        run: uv run --python 3.10 --extra dev mypy daisy
